// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejpahcbdvundfxqidcuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcGFoY2JkdnVuZGZ4cWlkY3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MTc0NDQsImV4cCI6MjA3ODI5MzQ0NH0.YzZozTW4KmS7qegJaz_UQVpcFc6cn_Hogjy-ndld1WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});